### ISSUE TITLE
Hi, my friend, I found a bug, but I don't know how to fix it.

### ISSUE THREAD

**Issue by DarkiT** [telemachus/humane#1]
Hi, my friend, I found a bug, but I don't know how to fix it.
```
  logger := sslog.New(humane.NewHandler(os.Stdout, nil))
  logger.Info("My informative message", "foo", "bar", "bizz", "buzz")
  logger.Error("Ooops", slog.Any("error", fmt.Errorf("xxxx")))
```

Expected output
```
  // Output:
  //  INFO | My informative message | foo=bar bizz=buzz time="2023-04-02T10:50.09 EDT"
  // ERROR | Ooops | error="error message" time="2023-04-02T10:50.09 EDT"
```

Actual output
```
  // Output:
 INFO | My informative message | foo=bar bizz=buzz time="2024-07-23T02:37.02 CST"
 INFO | Ooops | error=xxxx time="2024-07-23T02:37.02 CST" 
```

**Comment by telemachus** [comment]
Thank you! This was a very dumb bug: I was displaying [the handler's level](https://github.com/telemachus/humane/blob/main/humane.go#L177-L185) (which does not normally change) instead of the level of the specific record.

I have a fix, and I added tests for the problem. I should update sometime today. (I want to check things over just in case.) Thanks again for the report.

**Comment by telemachus** [comment]
@DarkiT I just uploaded a fix. Let me know if it gives you any trouble. Otherwise, I'll close this soon. Thanks again for the bug report.

**Comment by DarkiT** [comment]
> @DarkiT I just uploaded a fix. Let me know if it gives you any trouble. Otherwise, I'll close this soon. Thanks again for the bug report.

It now looks to be working perfectly. Thank you for your contribution.
